### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by Double-Click-ERP** [ITK-Leantime/leantime-estimateimport#11]
Hello ,
Thank you for this plugin

I got Error 500 after opening " Import To-Do's"

Log :

> [2024-12-05 10:35:52] production.ERROR: Target class [Leantime\Core\Template] does not exist. {"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target class [Leantime\\Core\\Template] does not exist. at /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Container/Container.php:914)
[stacktrace]
#0 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()
#1 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(963): Illuminate\\Container\\Container->resolve()
#2 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()
#3 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(948): Illuminate\\Container\\Container->make()
#4 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(181): Illuminate\\Foundation\\Application->make()
#5 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(124): Illuminate\\Container\\BoundMethod::addDependencyForCallParameter()
#6 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Container\\BoundMethod::getMethodDependencies()
#7 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#8 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#9 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#10 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#11 /var/www/html/leantime/app/Core/Controller/Controller.php(47): Illuminate\\Container\\Container->call()
#12 [internal function]: Leantime\\Core\\Controller\\Controller->__construct()
#13 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Container/Container.php(952): ReflectionClass->newInstanceArgs()
#14 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()
#15 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(963): Illuminate\\Container\\Container->resolve()
#16 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()
#17 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(948): Illuminate\\Container\\Container->make()
#18 /var/www/html/leantime/app/Core/Controller/Frontcontroller.php(182): Illuminate\\Foundation\\Application->make()
#19 /var/www/html/leantime/app/Core/Controller/Frontcontroller.php(83): Leantime\\Core\\Controller\\Frontcontroller->executeAction()
#20 /var/www/html/leantime/app/Core/Controller/Frontcontroller.php(91): Leantime\\Core\\Controller\\Frontcontroller->dispatch()
#21 /var/www/html/leantime/app/Core/Http/HttpKernel.php(128): Leantime\\Core\\Controller\\Frontcontroller::dispatch_request()
#22 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Leantime\\Core\\Http\\HttpKernel->Leantime\\Core\\Http\\{closure}()
#23 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/html/leantime/app/Core/Http/HttpKernel.php(128): Illuminate\\Pipeline\\Pipeline->then()
#25 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Leantime\\Core\\Http\\HttpKernel->Leantime\\Core\\Http\\{closure}()
#26 /var/www/html/leantime/app/Core/Middleware/LoadPlugins.php(31): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\LoadPlugins->handle()
#28 /var/www/html/leantime/app/Core/Middleware/Localization.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\Localization->handle()
#30 /var/www/html/leantime/app/Core/Middleware/SetCacheHeaders.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\SetCacheHeaders->handle()
#32 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#34 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#35 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#37 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#38 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#40 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
#42 /var/www/html/leantime/app/Core/Middleware/RequestRateLimiter.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\RequestRateLimiter->handle()
#44 /var/www/html/leantime/app/Core/Middleware/CurrentProject.php(32): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\CurrentProject->handle()
#46 /var/www/html/leantime/app/Core/Middleware/AuthCheck.php(99): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\AuthCheck->handle()
#48 /var/www/html/leantime/app/Core/Middleware/Updated.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\Updated->handle()
#50 /var/www/html/leantime/app/Core/Middleware/Installed.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\Installed->handle()
#52 /var/www/html/leantime/app/Core/Middleware/StartSession.php(128): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /var/www/html/leantime/app/Core/Middleware/StartSession.php(95): Leantime\\Core\\Middleware\\StartSession->handleStatefulRequest()
#54 /var/www/html/leantime/app/Core/Middleware/StartSession.php(64): Leantime\\Core\\Middleware\\StartSession->handleRequestWhileBlocking()
#55 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\StartSession->handle()
#56 /var/www/html/leantime/app/Core/Middleware/InitialHeaders.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\InitialHeaders->handle()
#58 /var/www/html/leantime/app/Core/Middleware/TrustProxies.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\TrustProxies->handle()
#60 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /var/www/html/leantime/app/Core/Http/HttpKernel.php(119): Illuminate\\Pipeline\\Pipeline->then()
#62 /var/www/html/leantime/app/Core/Http/HttpKernel.php(141): Leantime\\Core\\Http\\HttpKernel->sendRequestThroughRouter()
#63 /var/www/html/leantime/app/Core/Bootloader.php(87): Leantime\\Core\\Http\\HttpKernel->handle()
#64 /var/www/html/leantime/app/Core/Bootloader.php(68): Leantime\\Core\\Bootloader->handleRequest()
#65 /var/www/html/leantime/public/index.php(14): Leantime\\Core\\Bootloader->boot()
#66 {main}

>[previous exception] [object] (ReflectionException(code: -1): Class \"Leantime\\Core\\Template\" does not exist at /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Container/Container.php:912)
[stacktrace]
#0 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Container/Container.php(912): ReflectionClass->__construct()
#1 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()
#2 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(963): Illuminate\\Container\\Container->resolve()
#3 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()
#4 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(948): Illuminate\\Container\\Container->make()
#5 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(181): Illuminate\\Foundation\\Application->make()
#6 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(124): Illuminate\\Container\\BoundMethod::addDependencyForCallParameter()
#7 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Container\\BoundMethod::getMethodDependencies()
#8 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#9 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#10 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#11 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#12 /var/www/html/leantime/app/Core/Controller/Controller.php(47): Illuminate\\Container\\Container->call()
#13 [internal function]: Leantime\\Core\\Controller\\Controller->__construct()
#14 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Container/Container.php(952): ReflectionClass->newInstanceArgs()
#15 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()
#16 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(963): Illuminate\\Container\\Container->resolve()
#17 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()
#18 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(948): Illuminate\\Container\\Container->make()
#19 /var/www/html/leantime/app/Core/Controller/Frontcontroller.php(182): Illuminate\\Foundation\\Application->make()
#20 /var/www/html/leantime/app/Core/Controller/Frontcontroller.php(83): Leantime\\Core\\Controller\\Frontcontroller->executeAction()
#21 /var/www/html/leantime/app/Core/Controller/Frontcontroller.php(91): Leantime\\Core\\Controller\\Frontcontroller->dispatch()
#22 /var/www/html/leantime/app/Core/Http/HttpKernel.php(128): Leantime\\Core\\Controller\\Frontcontroller::dispatch_request()
#23 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Leantime\\Core\\Http\\HttpKernel->Leantime\\Core\\Http\\{closure}()
#24 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/html/leantime/app/Core/Http/HttpKernel.php(128): Illuminate\\Pipeline\\Pipeline->then()
#26 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Leantime\\Core\\Http\\HttpKernel->Leantime\\Core\\Http\\{closure}()
#27 /var/www/html/leantime/app/Core/Middleware/LoadPlugins.php(31): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\LoadPlugins->handle()
#29 /var/www/html/leantime/app/Core/Middleware/Localization.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\Localization->handle()
#31 /var/www/html/leantime/app/Core/Middleware/SetCacheHeaders.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\SetCacheHeaders->handle()
#33 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#35 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#36 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#38 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#39 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#41 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
#43 /var/www/html/leantime/app/Core/Middleware/RequestRateLimiter.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\RequestRateLimiter->handle()
#45 /var/www/html/leantime/app/Core/Middleware/CurrentProject.php(32): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\CurrentProject->handle()
#47 /var/www/html/leantime/app/Core/Middleware/AuthCheck.php(99): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\AuthCheck->handle()
#49 /var/www/html/leantime/app/Core/Middleware/Updated.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\Updated->handle()
#51 /var/www/html/leantime/app/Core/Middleware/Installed.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\Installed->handle()
#53 /var/www/html/leantime/app/Core/Middleware/StartSession.php(128): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /var/www/html/leantime/app/Core/Middleware/StartSession.php(95): Leantime\\Core\\Middleware\\StartSession->handleStatefulRequest()
#55 /var/www/html/leantime/app/Core/Middleware/StartSession.php(64): Leantime\\Core\\Middleware\\StartSession->handleRequestWhileBlocking()
#56 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\StartSession->handle()
#57 /var/www/html/leantime/app/Core/Middleware/InitialHeaders.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\InitialHeaders->handle()
#59 /var/www/html/leantime/app/Core/Middleware/TrustProxies.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Leantime\\Core\\Middleware\\TrustProxies->handle()
#61 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 /var/www/html/leantime/app/Core/Http/HttpKernel.php(119): Illuminate\\Pipeline\\Pipeline->then()
#63 /var/www/html/leantime/app/Core/Http/HttpKernel.php(141): Leantime\\Core\\Http\\HttpKernel->sendRequestThroughRouter()
#64 /var/www/html/leantime/app/Core/Bootloader.php(87): Leantime\\Core\\Http\\HttpKernel->handle()
#65 /var/www/html/leantime/app/Core/Bootloader.php(68): Leantime\\Core\\Bootloader->handleRequest()
#66 /var/www/html/leantime/public/index.php(14): Leantime\\Core\\Bootloader->boot()
#67 {main}
"}

**Comment by jeppekroghitk** [comment]
@Double-Click-ERP Sorry for the (very) late answer. 

Did you get it to work? Up front, the error message seems unrelated to the plugin.

**Comment by Double-Click-ERP** [comment]
Hello ,

now i got this error :

> [2025-06-24 13:56:09] production.ERROR: Leantime\Plugins\EstimateImport\Services\ImportHelper::saveDataToTempFile(): Argument #2 ($tempFilePath) must be of type string, null given, called in /var/www/html/leantime/app/Plugins/EstimateImport/Controllers/ImportMapping.php on line 76 {"exception":"[object] (TypeError(code: 0): Leantime\\Plugins\\EstimateImport\\Services\\ImportHelper::saveDataToTempFile(): Argument #2 ($tempFilePath) must be of type string, null given, called in /var/www/html/leantime/app/Plugins/EstimateImport/Controllers/ImportMapping.php on line 76 at /var/www/html/leantime/app/Plugins/EstimateImport/Services/ImportHelper.php:320)
[stacktrace]
#0 /var/www/html/leantime/app/Plugins/EstimateImport/Controllers/ImportMapping.php(76): Leantime\\Plugins\\EstimateImport\\Services\\ImportHelper->saveDataToTempFile()
#1 /var/www/html/leantime/app/Core/Controller/Controller.php(73): Leantime\\Plugins\\EstimateImport\\Controllers\\ImportMapping->post()
#2 /var/www/html/leantime/app/Core/Controller/Frontcontroller.php(184): Leantime\\Core\\Controller\\Controller->callAction()
#3 /var/www/html/leantime/app/Core/Controller/Frontcontroller.php(83): Leantime\\Core\\Controller\\Frontcontroller->executeAction()
#4 /var/www/html/leantime/app/Core/Controller/Frontcontroller.php(91): Leantime\\Core\\Controller\\Frontcontroller->dispatch()
#5 /var/www/html/leantime/app/Core/Http/HttpKernel.php(213): Leantime\\Core\\Controller\\Frontcontroller::dispatch_request()
#6 /var/www/html/leantime/app/Core/Http/HttpKernel.php(168): Leantime\\Core\\Http\\HttpKernel->findAndDispatchToRouter()
#7 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(170): Leantime\\Core\\Http\\HttpKernel->Leantime\\Core\\Http\\{closure}()
#8 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(127): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#9 /var/www/html/leantime/app/Core/Http/HttpKernel.php(168): Illuminate\\Pipeline\\Pipeline->then()
#10 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(170): Leantime\\Core\\Http\\HttpKernel->Leantime\\Core\\Http\\{closure}()
#11 /var/www/html/leantime/app/Domain/Projects/Middleware/CurrentProject.php(32): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(209): Leantime\\Domain\\Projects\\Middleware\\CurrentProject->handle()
#13 /var/www/html/leantime/app/Core/Middleware/Localization.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(209): Leantime\\Core\\Middleware\\Localization->handle()
#15 /var/www/html/leantime/app/Core/Middleware/SetCacheHeaders.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(209): Leantime\\Core\\Middleware\\SetCacheHeaders->handle()
#17 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#19 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(209): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#20 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(51): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#22 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(209): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#23 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(209): Illuminate\\Http\\Middleware\\ValidatePostSize->handle()
#25 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(209): Illuminate\\Http\\Middleware\\HandleCors->handle()
#27 /var/www/html/leantime/app/Core/Middleware/RequestRateLimiter.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(209): Leantime\\Core\\Middleware\\RequestRateLimiter->handle()
#29 /var/www/html/leantime/app/Core/Middleware/AuthenticateSession.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(209): Leantime\\Core\\Middleware\\AuthenticateSession->handle()
#31 /var/www/html/leantime/app/Core/Middleware/AuthCheck.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(209): Leantime\\Core\\Middleware\\AuthCheck->handle()
#33 /var/www/html/leantime/app/Core/Middleware/InitialHeaders.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(209): Leantime\\Core\\Middleware\\InitialHeaders->handle()
#35 /var/www/html/leantime/app/Core/Middleware/LoadPlugins.php(32): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(209): Leantime\\Core\\Middleware\\LoadPlugins->handle()
#37 /var/www/html/leantime/app/Core/Middleware/Updated.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(209): Leantime\\Core\\Middleware\\Updated->handle()
#39 /var/www/html/leantime/app/Core/Middleware/Installed.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(209): Leantime\\Core\\Middleware\\Installed->handle()
#41 /var/www/html/leantime/app/Core/Middleware/StartSession.php(173): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /var/www/html/leantime/app/Core/Middleware/StartSession.php(100): Leantime\\Core\\Middleware\\StartSession->handleStatefulRequest()
#43 /var/www/html/leantime/app/Core/Middleware/StartSession.php(70): Leantime\\Core\\Middleware\\StartSession->handleRequestWhileBlocking()
#44 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(209): Leantime\\Core\\Middleware\\StartSession->handle()
#45 /var/www/html/leantime/app/Core/Middleware/TrustProxies.php(65): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(209): Leantime\\Core\\Middleware\\TrustProxies->handle()
#47 /var/www/html/leantime/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(127): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/html/leantime/app/Core/Http/HttpKernel.php(159): Illuminate\\Pipeline\\Pipeline->then()
#49 /var/www/html/leantime/app/Core/Http/HttpKernel.php(117): Leantime\\Core\\Http\\HttpKernel->sendRequestThroughRouter()
#50 /var/www/html/leantime/app/Core/Bootloader.php(83): Leantime\\Core\\Http\\HttpKernel->handle()
#51 /var/www/html/leantime/app/Core/Bootloader.php(64): Leantime\\Core\\Bootloader->handleRequest()
#52 /var/www/html/leantime/public/index.php(20): Leantime\\Core\\Bootloader->boot()
#53 {main}
"}

**Comment by Double-Click-ERP** [comment]
Wow i am using V1.0.0

ok after update to 2.0.1 there is no error , however i couldn't see the task after imported (ps. Description in Arabic - Delimiter is , )

**Comment by Double-Click-ERP** [comment]
@jeppekroghitk 

i couldn't see the task after imported (ps. Description in Arabic - Delimiter is , )

**Comment by Double-Click-ERP** [comment]
@jeppekroghitk ??

**Comment by jeppekroghitk** [comment]
@Double-Click-ERP
You are welcome to troubleshoot it yourself and create a PR that implements the fix. Unfortunately, i don't have the time to do it.
